
skillMetadata:
  sections:
    - name: Login << Name of another section
      fields:
        - type: label
          label: The user you use to log into https://www.tado.com
        - name: username
          type: text
          label: TADO username
          value: ""
        - name: password
          type: password
          label: TADO password
          value: ""

    - name: TADO API
      fields:
        - type: label
          label: The latest CLIENT_SECRET can be found at https://my.tado.com/webapp/env.js

        - name: client_secret
          type: password
          label: Client Secret
          value: ""
          placeholder: your TADO Secret code